package pacote;




/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer indice;
     private String nome;
     private String email;
     private String cpf;
     private String telefone;

    public Pessoa() {
    }

    public Pessoa(String nome, String email, String cpf, String telefone) {
       this.nome = nome;
       this.email = email;
       this.cpf = cpf;
       this.telefone = telefone;
    }
   
    public Integer getIndice() {
        return this.indice;
    }
    
    public void setIndice(Integer indice) {
        this.indice = indice;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }




}


